---
- name: Run Kubernetes Manifest
  hosts: kubernetes-master
  become: true
  tasks:
    - name: Clone Git Repository
      git:
        repo: https://github.com/Dineshkumar07dk/kubernetes-poc.git
        dest: /home/ubuntu/kubernetes
        force: yes

    - name: Set Executable Permission for Shell Script
      file:
        path: /home/ubuntu/kubernetes/deploy.sh
        mode: '0777'
        owner: ubuntu
        group: ubuntu

    - name: Change Ownership of Directory
      become: true
      become_user: ubuntu
      file:
        path: /home/ubuntu/kubernetes-poc
        owner: ubuntu
        group: ubuntu
        recurse: yes

    - name: Execute Shell Script
      shell: /home/ubuntu/kubernetes/deploy.sh
