---
- name: Run Kubernetes Manifest
  hosts: kubernetes-master
  become: true
  tasks:
    - name: Clone Git Repository
      git:
        repo: https://github.com/Dineshkumar07dk/kubernetes-poc.git
        dest: /home/ubuntu/kubernetes
        force: yes
        
    - name: Apply Pod Manifest
      command: kubectl apply -f /home/ubuntu/kubernetes/pod.yml
      
    - name: Apply Deployment Manifest
      command: kubectl apply -f /home/ubuntu/kubernetes/Deployment.yml
      
    - name: Apply NodePort Service Manifest
      command: kubectl apply -f /home/ubuntu/kubernetes/nodeport.yml
