---
- name: Run Kubernetes Manifest
  hosts: kubernetes-master
  become: true
  tasks:
    - name: Clone Git Repository
      git:
        repo: https://github.com/Dineshkumar07dk/kubernetes-poc.git
        dest: /home/ubuntu/kubernetes
        force: yes
        
    - name: Execute deploy script
      command: /home/ubuntu/kubernetes/deploy.sh
