---
- name: Run Kubernetes Manifest
  hosts: kubernetes-master
  become: true
  tasks:
    - name: Clone Git Repository
      git:
        repo: https://github.com/Dineshkumar07dk/kubernetes-poc.git
        dest: /home/ubuntu/kubernetes
        force: yes
        
    - name: Copy deploy script
      copy:
        src: /home/ubuntu/deploy.sh
        dest: /tmp/deploy.sh
        mode: 0755

    - name: Execute deploy script
      command: /tmp/deploy.sh
